# Generated by Django 5.0.6 on 2024-06-26 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True,
                        help_text="Укажите место выполнения привычки",
                        null=True,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время выполнения привычки",
                        null=True,
                        verbose_name="Когда выполнить",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие привычки",
                        max_length=200,
                        verbose_name="Что выполнить",
                    ),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        default=False, verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("in 2 days", "Каждые 2 дня"),
                            ("in 3 days", "Каждые 3 дня"),
                            ("in 4 days", "Каждые 4 дня"),
                            ("in 5 days", "Каждые 5 дней"),
                            ("in 6 days", "Каждые 6 дней"),
                            ("weekly", "Еженедельно"),
                        ],
                        default="daily",
                        help_text="Укажите периодичность выполнения",
                        max_length=50,
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "award",
                    models.TextField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="Укажите длительность выполнения",
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите создателя привычки",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="good_habit",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
