# Generated by Django 5.0.6 on 2024-06-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                choices=[
                    ("cycling", "велопрогулка"),
                    ("water", "пить_воду"),
                    ("reading", "чтение"),
                    ("fitness", "фитнес"),
                ],
                help_text="Укажите действие привычки",
                max_length=200,
                verbose_name="Что выполнить",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("1", "Ежедневно"),
                    ("2", "Каждые 2 дня"),
                    ("3", "Каждые 3 дня"),
                    ("4", "Каждые 4 дня"),
                    ("5", "Каждые 5 дней"),
                    ("6", "Каждые 6 дней"),
                    ("weekly", "Еженедельно"),
                ],
                default="daily",
                help_text="Укажите периодичность выполнения",
                max_length=50,
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
